### PR TITLE
Updated Files.

### PR DESCRIPTION
**Pull request by Deepmalya3D**

### CODE REVIEW

**Comment by Roudranil** [comment]
Scoring ta merge korte chai na ami
Baki merge kora jabe ki?

**Comment by Deepmalya3D** [comment]
> Scoring ta merge korte chai na ami Baki merge kora jabe ki?

Merge kore version control diye change korte parbi ig

**Comment by Roudranil** [comment]
One sec ami koekta jinish kori, tarpor merge korchi

**Comment by Roudranil** [comment]
> > Scoring ta merge korte chai na ami Baki merge kora jabe ki?
> 
> Merge kore version control diye change korte parbi ig

Ei, ekta kaj kor, tui scoring baad diye baki ta pull request mar. Ota ke merge kore dichi

**Pull request merged**
